version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    networks:
      - my_shared_network

  magento:
    image: docker.io/bitnami/magento:2.4.6
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - SENTRY_ENV=local
      - MAGENTO_HOST=localhost:8080
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./magento_data:/bitnami/magento
      # - ./acuotaz_plugin:/bitnami/magento/vendor/apurata/financing
    depends_on:
      - mariadb
      - elasticsearch
    networks:
      - my_shared_network

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - './elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      - my_shared_network

volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  my_shared_network:
    external: true
